### ISSUE TITLE
A few areas names overflow the box

### ISSUE THREAD

**Issue by 1ted59** [teamrocketslime/RS3DS-Releases#8]
### Description
A few areas not listed in #1 overflow the box. The few I've found so far are:
Desert Wastes
Desert Wastes Harbor
Funadel Wastes Harbor

### Location of bug
(Saudi Arabia Area):
Desert Wastes
Desert Wastes Harbor

(North Europe Area):
Funadel Wastes Harbor

(Sahara Desert Area):
Seanile Tomb (Notably NOT Seanile Harbor)

### Screenshot
Sorry can't post screenshot currently, but for all two characters overflow the box.

### Additional Info
Will keep looking for more and update this issue if found

**Comment by CakeLancelot** [comment]
Thanks, I did have Funadel Wastes noted in #1 - but the others are new. Let me know if you find more. Should be able to take care of these for Beta 2.

**Comment by 1ted59** [comment]
Ah sorry, I wasn't sure whether the Harbor section was accounted for in Funadel Wastes versus just the regular area. That's why I didn't list the regular area. So for all of those listed in #1 the harbor overflows as well?

**Comment by CakeLancelot** [comment]
> I wasn't sure whether the Harbor section was accounted for in Funadel Wastes versus just the regular area. That's why I didn't list the regular area. So for all of those listed in #1 the harbor overflows as well?

I assume so - I will check and specify this in the future.

**Comment by 1ted59** [comment]
Just found an area where the harbor did not overflow but the inner area did (Senile Tomb).
I think the best way to deal with this is just to list every area and subarea, since they aren't both necessarily going to overflow at the same time.

**Comment by ultramario1998** [comment]
Fixed.

Changed 'Funadel Wastes Harbor' / 'Funadel Wastes' to 'Funadel Isle' (in keeping with overworld names) (This won't work for Desert Wastes, mostly because it's not an isle.)

Shortened 'Desert Wastes Harbor' to 'Desert Wastes Hbr.'.

Expanded in-map names + nameplate pane size for Desert Wastes, Seanile Tomb, and Funadel Isle - they should all show up properly in the next build.

Closing issue for now. If OP comes across any more issues of this type, feel free to reopen.
